apiVersion: v1
kind: Pod
metadata:
  name: deeplearning
spec:
  containers:
    - name: jetson-tensorflow
      image: nvcr.io/nvidia/l4t-base:r32.4.2
      command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]